# -*- coding: utf-8 -*-
"""01-IntroToPython_Lab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/136tpSCsnhusFIALJvYTj3TOmxyiou5ai

# Intro to Python Lab
1.   make a new private github project
2.   Save this notebook to a that project
3.   Answer the following python questions.
4.   Then push the new version of this document to your github project
5.   Share your github repository with one person from the class, ask them to share their repository with you too. 
6.   Check each other's code
3.   At the end of the notebook of your peer, add a new Text Cell writing "Well done!!" and push it to their repository

## WELL DONE!
"""

# STARTER CODE:
x = "Coding in python is so much fun! Python will be my new superpower!"
y = 3
z = 3.0

# Q1:  
# What is the type of the variable x
type(x)
# How many characters are there in the variable x? (You need to discover a new string function to answer this!)
len(x)

# Q2:  Print out the variable x in all upper case
x.upper()

# Q3:  Print the number of times the word python exists in the variable x.
# HINT:  you may need to change the case to find the instances
# Python is case sensitive.
# You will also need to discover a new string function to answer this!

string = x.lower()
substring = "python"

count = string.count(substring)

# print count
print("The count is:", count)

# Q4:  Are the variables y and z equal?

print((x) == (y))

"""# Question 5

Below there are two blocks of code to help you get started with the last question. We will cover installing and importing modules later on, but below is a really awesome package that lets us parse news articles!
"""

# Q5 starter code 1:
! pip install newspaper3k

# Q5 starter code 2
from newspaper import Article
URL = "https://www.boston.com/travel/travel/2020/09/18/logan-airport-contactless-food-delivery"
article = Article(URL)
article.download()
article.parse()
article_text = article.text



# Q5A:  print the variable article_text
print(article.text)

# Q5B: What is the data type for article_text?
type(article_text)

# Q5C: Save the lower case version of article text to a new variable, article_lower
lowercase=article_text.lower()
print(lowercase)

# Q5D: How many times does the word Logan appear in the variable article_lower?

substring1 ="Logan"

count = lowercase.count(substring1)

substring2 ="logan"
count2 = lowercase.count(substring2)

# print count
print("The count is:", count,"when Logan is used and ", count2," when logan is used")

